[package]
name = "rsrl"
description = "A fast, extensible reinforcement learning framework in Rust"

version = "0.4.2"
authors = ["Tom Spooner <t.spooner@liverpool.ac.uk>"]

license = "MIT"
readme = "README.md"

keywords = ["machine", "reinforcement", "learning", "rl", "ai"]

repository = "https://github.com/tspooner/rsrl"
documentation = "https://docs.rs/rsrl"

[badges]
travis-ci = { repository = "tspooner/rsrl", branch = "master" }
coveralls = { repository = "tspooner/rsrl", branch = "master", service = "github" }

[dependencies]
lfa = "0.2"
spaces = "0.0"

rand = "0.4"
cpython = "0.1"
ndarray = { version = "0.11", features = ["blas", "serde-1"] }

serde = "1.0"
serde_derive = "1.0"

slog = "2.1"
slog-term = "2.3"
slog-async = "2.2"

blas = "0.19"
openblas-src = "0.5"

[dev-dependencies]
serde_test = "1.0"
