[package]
name = "rsrl"
description = "A fast, extensible reinforcement learning framework in Rust"

version = "0.2.2"
authors = ["Tom Spooner <t.spooner@liverpool.ac.uk>"]

license = "MIT"
readme = "README.md"

keywords = ["machine", "reinforcement", "learning", "rl", "ai"]

repository = "https://github.com/tspooner/rsrl"
documentation = "https://tspooner.github.io/rsrl/rsrl/index.html"

[badges]
travis-ci = { repository = "tspooner/rsrl", branch = "master" }
coveralls = { repository = "tspooner/rsrl", branch = "master", service = "github" }

[dependencies]
log = "0.4"
rand = "0.4"
time = "0.1"
cpython = "0.1"
rusty-machine = "0.5"

serde = "1.0"
serde_json = "1.0"
serde_test = "1.0"
serde_derive = "1.0"

slog = "2.0"
slog-term = "2.3"
slog-async = "2.1"

blas = "0.19"
openblas-src = "0.5"

ndarray = { version = "0.11", features = ["blas", "serde-1"] }

[dev-dependencies]
seahash = "3.0"
