[package]
name = "rsrl"
version = "0.0.0"
authors = ["Tom Spooner <t.spooner@liverpool.ac.uk>"]
license = "MIT"
readme = "README.md"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
log = "0.3"
blas = "0.15"
libc = "0.2"
rand = "0.3"
time = "0.1"
ndarray = "0.9"
indicatif = "0.3"
